### ISSUE TITLE
PPU Loading time

### ISSUE THREAD

**Issue by TekSupreme** [DAGINATSUKO/www-rpcs3#102]
Last weeks version takes about 1 minute for complete PPU compilation and works just fine. Latest update takes 10 or 15 minutes for PPU compilation just use old build from last week. Developer please add feature to turn off update notifications thanks in advance. PPU Loading time is annoying in this emulator glad I still own a working PS3 console. Please try to make PPU save into emulator file so it can have instant boot.

**Comment by AniLeo** [comment]
This has nothing to do with rpcs3-www.
