### ISSUE TITLE
(Bug) The "All" filter is ignored if using letter-based search on the "Compatibility" page

### ISSUE THREAD

**Issue by hardBSDk** [DAGINATSUKO/www-rpcs3#110]
It only show playable games and ignore the "All" filter.

## How To Reproduce

- Open the "Compatibility" page
- Verify if the "All" filter is used in all items
- Click on the "G" letter
- Click on the section 2 and try to find God Of War 3

## System Information

- Web Browser - Firefox (latest version)
- OS - Fedora 40

![image](https://github.com/DAGINATSUKO/www-rpcs3/assets/55782009/a05133be-251a-49c5-9c58-e8d7891ed405)

![image](https://github.com/DAGINATSUKO/www-rpcs3/assets/55782009/f3506c74-05f0-451e-bb33-fa87cdabde36)

**Comment by AniLeo** [comment]
Cannot see what sorting you're using from your screenshot.

Default sorting is **status, title ASC**, so it is correct that you don't see GoW3 by default since it's not Playable.

**Comment by hardBSDk** [comment]
@AniLeo I mentioned that I'm using the "All" filter in all items.

I have more information about the bug, when I don't search the games using the letters, they show the total number of games for each status, but when I click some letter, this number reduces a lot, it's expected?

When I search the game name, it appears, thus the bug only happens with letter search.

It basically ignore the "All" filter in status, if I use "Ingame", the game is shown.

**Comment by hardBSDk** [comment]
@AniLeo I updated the issue title and description, sorry for the lack of details.

**Comment by AniLeo** [comment]
It's not about filtering, it's about sorting. There's no bug here as I explained, the default sort is **status, title ASC** by design, not by mistake. 

If you want to sort by title independent of status you need to click on "Game Title" in the table headers. I just tested and both the default and non default sorting options are working fine.
