### ISSUE TITLE
List of PCSX2/Duckstation style games

### ISSUE THREAD

**Issue by carlosgamer23** [DAGINATSUKO/www-rpcs3#114]
Could you please give us the opportunity to use our own box arts in the game list? Something similar to PCSX2/Duckstation. Congratulations on all your work!

**Comment by AniLeo** [comment]
There's nowhere in the compatibility list I can imagine box art images looking well in the game entries

You can already add them on the wiki pages for the game, ultimately if we need to display them on the compatibility list at some point down the line we will source them from there
