### ISSUE TITLE
The TSX-NI Wikipedia link cannot be clicked in the Quickstart guide

### ISSUE THREAD

**Issue by nitrohigito** [DAGINATSUKO/www-rpcs3#20]
Due to the `noevent` class of the divs, the TSX-NI's Wikipedia link cannot be clicked.

![image](https://user-images.githubusercontent.com/10439488/43338123-d33f6c7a-91d5-11e8-88b6-18327eae6451.png)

**Comment by DAGINATSUKO** [comment]
Fixed
