### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by ibrakap** [DAGINATSUKO/www-rpcs3#26]
Can you add po files for translation?

**Comment by DAGINATSUKO** [comment]
Unfortunately translations aren't something we're working on due to the time and maintenance required to work with contributors to translate different parts of the website that are updated frequently. We are however looking into an automated system for this.

**Comment by DAGINATSUKO** [comment]
Unfortunately translations aren't something we're working on due to the time and maintenance required to work with contributors to translate different parts of the website that are updated frequently. We are however looking into an automated system for this.
