### ISSUE TITLE
add PC Specs to user postbit in Forums

### ISSUE THREAD

**Issue by uaqlover** [DAGINATSUKO/www-rpcs3#27]
just a suggestion 

![ice_screenshot_20190207-050339](https://user-images.githubusercontent.com/45731484/52384182-d2677500-2a95-11e9-92cc-04a7dc0a72bf.png)

![6](https://user-images.githubusercontent.com/45731484/52384263-240fff80-2a96-11e9-90af-afcdac93b675.png)
![7](https://user-images.githubusercontent.com/45731484/52384274-38ec9300-2a96-11e9-88f1-d625c7f655b3.png)

**Comment by DAGINATSUKO** [comment]
The forums are handled by @AniLeo. You'll have to get in contact with him for this suggestion.
