### ISSUE TITLE
[Feature Request] Keep position on page after compat search

### ISSUE THREAD

**Issue by Megamouse** [DAGINATSUKO/www-rpcs3#54]
When applying a search in the compatibility list, the current page is reloaded and the view jumps back to the top.
I think it would be nice if the page kept its current position instead (or jumped to the search area), so that you don't have to scroll down after every search.

### Current view before search:
![image](https://user-images.githubusercontent.com/23019877/85943443-745c5b80-b930-11ea-801d-59a655794301.png)

### Current view after search:
![image](https://user-images.githubusercontent.com/23019877/85943469-90f89380-b930-11ea-8e79-b904a05dd0ec.png)

**Comment by DAGINATSUKO** [comment]
Compatibility is completely developed by Ani (aside from some styling). You can find his repo [here](https://github.com/AniLeo/rpcs3-compatibility). I spoke to him about adding something like this and it's currently [live](https://rpcs3.net/compatibility).
