### ISSUE TITLE
Extreme load

### ISSUE THREAD

**Issue by laptopleon** [DAGINATSUKO/www-rpcs3#56]
Hi,

I noticed the site uses an extreme percentage of cpu power. For example the FAQ page is completely static, except for a subtle background animation, yet it puts the cpu of my computer on 135% in Firefox and 220% in Safari. Makes the fans spin, seriously heats up, etc. In comparison, this doesn't even happen with a HD youtube video.

Regards,
Leon

**Comment by DAGINATSUKO** [comment]
You can use the settings menu in the top right corner of the page to disable CPU/GPU related effects on the page, though these effects aren't nearly as intensive as you are describing. At most, 10% of the CPU would be used to render the effects on a quad core CPU at a modest clock speed. On mobile, these effects are completely disabled.
