### ISSUE TITLE
[Request] Add compatible Blu-ray drive to quickstart

### ISSUE THREAD

**Issue by Lagahan** [DAGINATSUKO/www-rpcs3#63]
I have a model of blu-ray drive that isn't listed as compatible in the quickstart guide, but I've dumped my whole library with it no problem:

Lite-on/Phillips DS-6E2SH19C

Its a slim laptop drive and 19C is the revision.

**Comment by DAGINATSUKO** [comment]
Thank you. I've added this drive to the list.
