### ISSUE TITLE
Register rpcs3.net to take donations from Brave Rewards?

### ISSUE THREAD

**Issue by XenoFantom** [DAGINATSUKO/www-rpcs3#65]
Brave Browser basically has a feature that lets you donate to websites. However, in order for a website to receive donations, they have to register in the program. Thought this would help RPCS3.

https://creators.brave.com/

**Comment by DAGINATSUKO** [comment]
Hello. Sorry for the late response, but after talking to the team, we currently aren't interested in this type of program due to the complexity and market share of the Brave browser being much smaller than other browsers.

**Comment by XenoFantom** [comment]
Okay, thank you for your response.
