### ISSUE TITLE
Bad performance score in https://web.dev/measure

### ISSUE THREAD

**Issue by IngrownMink4** [DAGINATSUKO/www-rpcs3#67]
I tested RPCS3.net in https://web.dev/measure and this are the results:
https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Frpcs3.net%2F

![firefox_9elwjSa2HC](https://user-images.githubusercontent.com/25466522/110244073-5930f980-7f5d-11eb-949b-fde225e2fd37.png)

- **Performance = 44**
- Accessibility = 91
- Best practices = 80
- SEO = 100

As you can see, RPCS3.net has bad results in performance. I don't know why this happen but I thought it would be a good idea to mention it here so that you can get over it :)

**Comment by DAGINATSUKO** [comment]
Thank you for your concern. I've been working on various optimizations for a little while and they will be implemented in due time.
