### ISSUE TITLE
[Request] Add drive to the compatibility list

### ISSUE THREAD

**Issue by ProbablyLotte** [DAGINATSUKO/www-rpcs3#69]
LG Slim Portable Blu-ray / DVD Writer
Model: WP50NB40
ROM Ver. 1.03

Used 13xforever's PS3 Dumper, then manually verified the IRD with PS3-ISO-Rebuilder 1.0.4.1 to make sure.

**Comment by DAGINATSUKO** [comment]
Sorry for the late reply, I've added the drive. Thank you!
