### ISSUE TITLE
Missaligned span "build-tx2-label" in index.php

### ISSUE THREAD

**Issue by Jesperson** [DAGINATSUKO/www-rpcs3#71]
![bild](https://user-images.githubusercontent.com/14894497/138168448-8903d5a4-110b-4f77-9d3a-7f15f111d970.png)
Text not aligned, fixed by:
.build-tx2-label {
    font-family: Roboto-Regular;
    background: #1abc9c;
    padding: 4px 8px;
    border-radius: 30px;
    margin-left: 4px;
    margin-right: 0px;
    color: #fff;
}
in main.css

I didn't feel it was necessary to make an entire PR for 1 css change and I'm not sure it's the optimal change either.
Edit: Tested it on both a 4k-monitor and 1080p-monitor with the same issue on both.

**Comment by Jesperson** [comment]
Using Firefox 93.0 (Latest I know of)

**Comment by DAGINATSUKO** [comment]
Should be fixed now, thanks for letting me know
