### ISSUE TITLE
Consider Replacing Download Button Icon

### ISSUE THREAD

**Issue by NayamAmarshe** [DAGINATSUKO/www-rpcs3#83]
I'm on ZorinOS and when I saw the Windows icon on the download button I thought the website is not detecting my UA string correctly and thought it was a bug. Apparently the icon changes every second or so but it was a bit too late for me to realize that as I had scrolled down, trying to find if Linux is even supported (I was in a bit of a hurry so didn't read the subheading)
![image](https://user-images.githubusercontent.com/25067102/169470345-0e143403-8bf7-45d6-bb68-9157303d87a7.png)

I suggest replacing the dynamic button icons with an RPSC3 logo or detect the platform from the UA to avoid confusion.

**Comment by DAGINATSUKO** [comment]
Well, I do the dynamic icons just for the sake of letting the user known we support these platforms, etc. I will look into a solution to display an icon based on OS.
