### ISSUE TITLE
RPCS3 main site or github changelog history Pull Request link

### ISSUE THREAD

**Issue by Augusto7743** [DAGINATSUKO/www-rpcs3#85]
When an RPCS3 new version is released some users open links from https://rpcs3.net/compatibility?b in section Pull Request thus opening an link to changes for an download release.
If user wish see all changes for previous versions need open an link for each Pull Request.

One address link showing all versions changelog is an good solution and is better to read.
Thanks for read.
Have an nice day.

**Comment by DAGINATSUKO** [comment]
Hello. You can probably open a request on the Compatibility repo for such a feature here: [https://github.com/AniLeo/rpcs3-compatibility](https://github.com/AniLeo/rpcs3-compatibility)

I only handle the core website and not the compatibility pages.

**Comment by Augusto7743** [comment]
Thanks very much for your reply.
I will try post in rpcs3-compatibility.

Have an nice week.
