### ISSUE TITLE
linux.org License Violation

### ISSUE THREAD

**Issue by Alex-Sour** [DAGINATSUKO/www-rpcs3#87]
As stated in #82, the license of the Linux logo on the downloads button from linux.org is not allowed to be used.

https://www.linux.org/threads/linux-org-logo-licensing.40445/

This is a problem.

My suggestions:

- Ask linux.org team is the logo can be used (after all that time, they may have changed their minds, or maybe they would be willing to accept it to be used in certain cases, such as platform icons
- Give up GitHub and move to Gitea
- Leave it as-is and suffer the consequences
- Change it to Tux

**Comment by Alex-Sour** [comment]
Actually, checking the thread linked again, it seems the recreation may be fine to use given it is a derivative of the linux.org logo following the redraw. Perhaps this may influence your fate?

**Comment by DAGINATSUKO** [comment]
I've changed the icons to Tux, should be live on cache in an hour or so.

![image](https://user-images.githubusercontent.com/25255270/184666775-5a601997-dc48-4d50-8575-296c51a7b8ea.png)

**Comment by Alex-Sour** [comment]
Alright

It is unfortunate that the logo license does not permit usage, as it looked very nice.
