### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by xMatrixxx** [DAGINATSUKO/www-rpcs3#88]
Hello, can I make the dark theme the default?  So that the user initially had a dark theme, and if desired, he could change it.  How can I do that?

**Comment by DAGINATSUKO** [comment]
Dark theme by default would be nice, I'll try to look into a solution where I can detect the systems current light mode setting and apply it by default.

**Comment by xMatrixxx** [comment]
I used this code:
`if(!isset($_COOKIE['save-darkmode'])) {
	setcookie("save-darkmode", "true");
}


?><<!doctype html>`
In index.php
